'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
export function CenterPanel({onSelect,uz=false}:{onSelect:(id:string)=>Promise<void>;uz?:boolean}){
 const t=(en:string,local:string)=>uz?local:en;
 const [centers,setCenters]=useState<any[]>([]),[name,setName]=useState(''),[codes,setCodes]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function reload(){const r=await fetch('/api/centers',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error);setCenters(d.centers)}
 useEffect(()=>{reload().catch(e=>setError(e.message))},[]);
 return <section className="centers-panel" style={{display:'grid',gap:24,minWidth:0}}><p style={{margin:0}}>{t('Owner sees every centre. Teachers and students see only their own centre.','Owner barcha markazlarni ko‘radi. O‘qituvchi va o‘quvchilar faqat o‘z markazini ko‘radi.')}</p>{error&&<p className="error">{error}</p>}<form style={{display:'grid',gap:16,maxWidth:640,width:'100%'}} onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/centers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})}),d=await r.json();if(!r.ok)throw new Error(d.error);setCodes(d);setName('');await reload()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label>{t('New learning centre','Yangi o‘quv markazi')}<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><div><Button disabled={busy} type="submit">{t('Add centre','Markaz qo‘shish')}</Button></div></form>{codes&&<p className="feedback correct">{codes.name} added. Existing shared Teacher and Centre Manager codes apply.</p>}<div><Button variant="outline" onClick={()=>onSelect('')}>{t('View all centres','Barcha markazlarni ko‘rish')}</Button></div><div className="group-grid" style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,300px),1fr))',gap:20}}>{centers.map(c=><article className="group-card" key={c.id} style={{display:'flex',flexDirection:'column',alignItems:'flex-start',gap:16,margin:0,minWidth:0}}><h3 style={{margin:0,overflowWrap:'anywhere'}}>{c.name}</h3><p style={{margin:0}}>{c.teachers} {t('teachers','o‘qituvchi')} · {c.students} {t('students','o‘quvchi')}</p><Button onClick={()=>onSelect(c.id)}>{t('Open centre','Markazni ochish')}</Button></article>)}</div></section>
}

export function MoveCenter({userId,currentCenter,onMoved}:{userId:string;currentCenter:string;onMoved:()=>Promise<void>}){
 const [centers,setCenters]=useState<any[]>([]),[id,setId]=useState(currentCenter),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{setId(currentCenter);fetch('/api/centers',{cache:'no-store'}).then(r=>r.json()).then(d=>setCenters(d.centers||[])).catch(()=>setError('Could not load centres.'))},[userId,currentCenter]);
 return <section className="assignment"><h3>Learning centre — Owner only</h3><label>Centre<select value={id} onChange={e=>setId(e.target.value)}>{centers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><p>The account and its private progress move together. Its group is cleared and it signs out.</p><Button disabled={busy||id===currentCenter} onClick={async()=>{setBusy(true);setError('');try{const r=await fetch('/api/centers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'moveUser',userId,centerId:id})}),d=await r.json();if(!r.ok)throw new Error(d.error);await onMoved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>Move account</Button>{error&&<p className="error">{error}</p>}</section>
}
