'use client';
import {useEffect,useRef,useState} from 'react';
import {answerEnter,useAnswerEnterBody} from './answer-key';
import {Button} from '@/components/ui/button';
import {learning,AskTeacher} from './workspace';
import {playbackRate} from '@/lib/audio-settings';
import {correct,type Task,type LessonPack} from '@/lib/learning';
let voicePlayer:HTMLAudioElement|null=null,voiceUrl='',voiceSequence=0,voiceRequest:AbortController|null=null;
const voiceCache=new Map<string,Blob>();
export function stopVoice(){voiceSequence++;voiceRequest?.abort();voiceRequest=null;voicePlayer?.pause();voicePlayer=null;if(voiceUrl)URL.revokeObjectURL(voiceUrl);voiceUrl='';window.speechSynthesis?.cancel();}
export async function say(text:string,rate=.7,language:'uz'|'en'='en',done?:()=>void){
 stopVoice();const seq=voiceSequence,key=language+'|'+text.slice(0,1200);
 // Short instructions use the installed voice immediately when available.
 const voices=window.speechSynthesis?.getVoices()||[],local=voices.find(v=>v.lang.toLowerCase().startsWith(language==='uz'?'uz':'en')&&/natural|google|online/i.test(v.name))||voices.find(v=>v.lang.toLowerCase().startsWith(language==='uz'?'uz':'en'));

 const controller=new AbortController();voiceRequest=controller;const timer=setTimeout(()=>controller.abort(),8000);
 try{let blob=voiceCache.get(key);if(!blob){const r=await fetch('/api/voice',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:text.slice(0,1200),language}),signal:controller.signal});if(!r.ok)throw new Error('Voice unavailable');blob=await r.blob();if(voiceCache.size>=24)voiceCache.delete(voiceCache.keys().next().value!);voiceCache.set(key,blob)}if(seq!==voiceSequence)return;voiceUrl=URL.createObjectURL(blob);voicePlayer=new Audio(voiceUrl);voicePlayer.preservesPitch=true;voicePlayer.playbackRate=playbackRate(rate);voicePlayer.onended=()=>{if(seq===voiceSequence)done?.()};await voicePlayer.play();
 }catch{if(seq!==voiceSequence)return;if(language==='uz'&&!local){window.dispatchEvent(new Event('zamon-uz-voice-unavailable'));done?.();return}if(!window.speechSynthesis)return;window.dispatchEvent(new Event('zamon-browser-voice'));const speech=new SpeechSynthesisUtterance(text);speech.lang=language==='uz'?'uz-UZ':'en-GB';if(local)speech.voice=local;speech.rate=playbackRate(rate);speech.onend=()=>{if(seq===voiceSequence)done?.()};window.speechSynthesis.speak(speech)}finally{clearTimeout(timer);if(voiceRequest===controller)voiceRequest=null}
}
export function taskInstruction(q:Task){const instructions={choice:'Inglizcha gapni tinglang. Keyin uning to‘g‘ri o‘zbekcha ma’nosini tanlang.',letters:'Harflarni kerakli tartibda bosib, inglizcha so‘zni yig‘ing.',order:'So‘zlarni kerakli tartibda tanlab, inglizcha gap tuzing.',dictation:'Listen tugmasini bosing. Eshitgan inglizcha so‘z yoki gapni yozing.',punctuation:'Bo‘sh joy yoki tinish belgisini tanlang. Keyin kerakli harflar orasini bosing yoki belgini o‘sha joyga olib boring.',speaking:'Savolni tinglang. Mikrofon tugmasini bosing va inglizcha javob bering.'};return instructions[q.kind]+(q.review?' Bu avval qiynalgan mashqingizni takrorlash.':'')}

function record(result:(s:string)=>void,error:(s:string)=>void){const R=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;stopVoice();if(!R){error('Please use Chrome or Edge and allow microphone access.');return null}const r=new R();r.lang='en-GB';r.onresult=(e:any)=>result(e.results[0][0].transcript);r.onerror=(e:any)=>error(e.error==='not-allowed'?'Allow microphone access in browser site permissions.':'Could not hear you. Please retry.');r.start();return r;}
export function TaskCard({q,answer,onChange,disabled}:{q:Task;answer:string;onChange:(v:string)=>void;disabled:boolean}){
 const [selected,setSelected]=useState(' '),[tiles,setTiles]=useState<number[]>([]);useEffect(()=>{setTiles([]);setSelected(' ')},[q.id]);
 if(q.kind==='choice')return <div className="options">{q.options?.map(o=><button disabled={disabled} key={o} className={answer===o?'selected':''} onClick={()=>onChange(o)}>{o}</button>)}</div>;
 if(q.kind==='letters'||q.kind==='order'){const tokens=q.kind==='letters'?[...q.answer]:q.answer.replace(/[.!?]$/,'').split(' '),pool=tokens.map((s,i)=>({s,i})).reverse();return <><div className="assembly-answer" aria-live="polite">{answer||'…'}</div><div className="tile-bank">{pool.map(({s,i})=><button key={i} disabled={disabled||tiles.includes(i)} onClick={()=>{const next=[...tiles,i];setTiles(next);onChange(next.map(j=>tokens[j]).join(q.kind==='letters'?'':' '))}}>{s}</button>)}</div><Button variant="outline" disabled={disabled} onClick={()=>{setTiles([]);onChange('')}}>Reset</Button></>}
 if(q.kind==='punctuation'){const raw=q.answer.replace(/[\s.,!?;:]/g,''),positions=new Map<number,string>();let i=0;for(const ch of answer){if(/[\s.,!?;:]/.test(ch))positions.set(i,(positions.get(i)||'')+ch);else i++}function place(index:number,symbol=selected){const old=positions.get(index)||'';positions.set(index,symbol===' '?old.replace(/\s/g,'')+' ':symbol?symbol+(old.includes(' ')?' ':''):'');let value=positions.get(0)||'';for(let j=0;j<raw.length;j++)value+=raw[j]+(positions.get(j+1)||'');onChange(value)}return <><div className="tile-bank">{[' ','.',',','?','!',''].map(s=><button key={s} disabled={disabled} className={selected===s?'selected':''} draggable onDragStart={e=>e.dataTransfer.setData('text/plain',s)} onClick={()=>setSelected(s)}>{s===' '?'␣':s||'⌫'}</button>)}</div><p>Belgini tanlang, keyin kerakli oraliqni bosing. Belgini sudrab olib borishingiz ham mumkin.</p><div className="punctuation-line">{[...raw].map((c,j)=><span key={j}>{j===0&&<button disabled={disabled} aria-label="Before first letter" onClick={()=>place(0)}>{positions.get(0)||'·'}</button>}{c}<button disabled={disabled} aria-label={'Gap '+(j+1)} onClick={()=>place(j+1)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const s=e.dataTransfer.getData('text/plain');if(![' ','.',',','?','!',''].includes(s))return;place(j+1,s)}}>{positions.get(j+1)||'·'}</button></span>)}</div><div className="assembly-answer">{answer||raw}</div><Button variant="outline" disabled={disabled} onClick={()=>onChange('')}>Reset</Button></>}
 if(q.kind==='speaking')return <><Button disabled={disabled} onClick={()=>record(onChange,e=>alert(e))}>🎙 Speak</Button><p className="speech-transcript">{answer||'Your recognised speech appears here.'}</p><small>Speech recognition is approximate.</small></>;
 return <textarea data-answer-input rows={2} disabled={disabled} value={answer} onChange={e=>onChange(e.target.value)} aria-label="Answer" autoComplete="off"/>;
}
export function Journey({book,unit,lesson,rate,uz,onBack,onFinish,resumeStage=0}:{book:string;unit:number;lesson:string;rate:number;uz:boolean;onBack:()=>void;onFinish:()=>Promise<void>;resumeStage?:number}){
 useAnswerEnterBody();
 const test=lesson==='test';const [content,setContent]=useState<LessonPack|null>(null),[tasks,setTasks]=useState<Task[]>([]),[session,setSession]=useState(''),[stage,setStage]=useState(test?3:resumeStage),[index,setIndex]=useState(0),[answer,setAnswer]=useState(''),[answers,setAnswers]=useState<string[]>([]),[first,setFirst]=useState<string[]>([]),[checked,setChecked]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[chat,setChat]=useState<{role:string;text:string}[]>([]),[chatInput,setChatInput]=useState(''),[result,setResult]=useState<any>(null),[rating,setRating]=useState(''),[voiceEnabled,setVoiceEnabled]=useState(false);const started=useRef(Date.now()),rec=useRef<any>(null);const t=(a:string,b:string)=>uz?b:a;const [browserVoice,setBrowserVoice]=useState(false),[uzVoiceError,setUzVoiceError]=useState(false);useEffect(()=>{const f=()=>setBrowserVoice(true);const missing=()=>setUzVoiceError(true);window.addEventListener('zamon-browser-voice',f);window.addEventListener('zamon-uz-voice-unavailable',missing);return()=>{window.removeEventListener('zamon-browser-voice',f);window.removeEventListener('zamon-uz-voice-unavailable',missing)}},[]);
 async function start(){setBusy(true);setError('');try{const d=await learning({action:'start',book,unit,lesson});setSession(d.session);setContent(d.content);setTasks(d.tasks);if(d.content)setChat([{role:'ai',text:d.content.dialogue}]);if(d.state){setStage(d.state.stage);setIndex(d.state.index);setAnswer(d.state.answer||'');setAnswers(d.state.answers||[]);setFirst(d.state.first||[]);setChecked(!!d.state.checked);if(d.state.chat)setChat(d.state.chat)}else setStage(test?3:0)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{start();return()=>{rec.current?.abort();stopVoice()}},[]);
 useEffect(()=>{if(session)learning({action:'bookmark',book,unit,lesson,stage}).catch(()=>{})},[stage,session]);
 useEffect(()=>{if(!session||result)return;const timer=setTimeout(()=>learning({action:'saveState',session,state:{stage,index,answer,answers,first,checked,chat}}).catch(()=>{}),600);return()=>clearTimeout(timer)},[session,stage,index,answer,answers,first,checked,chat,result]);
 const labels=['Welcome','Words','Structures','Practice','AI conversation','Speaking','Review','How was your lesson?'];const q=tasks[index];
 const instruction=stage===3&&q?taskInstruction(q):stage===1?'Bu yerda yangi so‘zlarni o‘rganasiz. So‘zning ma’nosi va misolini o‘qing. So‘z yonidagi ovoz belgisini bosib, talaffuzini eshiting.':stage===2?content?.explanation||'Gap tuzilishiga e’tibor bering. Misollarni o‘qing va tinglang.':stage===4?'AI savoliga inglizcha javob bering. Javobni yozishingiz yoki mikrofon orqali aytishingiz mumkin.':stage===5?'Mikrofon tugmasini bosib, AI bilan inglizcha suhbatlashing.':stage===6?'O‘rgangan so‘zlar va gap tuzilmalarini qayta ko‘rib chiqing.':stage===7?test?'Test tugadi. Natijangizni saqlash uchun Tugatish tugmasini bosing.':'Dars qanday bo‘lganini belgilang. Keyin Tugatish tugmasini bosing.':'Darsni boshlaymiz. Avval so‘zlarni o‘rganamiz, keyin gap tuzish va suhbatni mashq qilamiz.';


 async function sendChat(input:string){if(!input.trim())return;stopVoice();setBusy(true);setError('');try{const d=await learning({action:'chat',book,unit,lesson,input,history:chat});setChat(v=>[...v,{role:'user',text:input},{role:'ai',text:d.text}]);setChatInput('');stopVoice()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function finish(){setBusy(true);try{const d=await learning({action:'finish',session,answers,firstAnswers:first,seconds:Math.round((Date.now()-started.current)/1000),rating});setResult(d);await onFinish()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="journey" onKeyDown={answerEnter}><button className="back" onClick={onBack}>← {t('Back','Orqaga')}</button><div className="practice-top"><strong>{lesson==='test'?t('Unit test','Unit testi'):lesson+' · '+labels[stage]}</strong></div><button className="text-button" onClick={stopVoice}>■ {t('Stop voice','Ovozni to‘xtatish')}</button>{uzVoiceError&&<small role="status">O‘zbekcha ovoz hozir ishlamadi. Quyidagi tushuntirishni o‘qing yoki Tushuntirish tugmasini qayta bosing.</small>}<p className="assignment" lang="uz">{instruction}</p>{browserVoice&&<small role="status">{t('AI ovozi ishlamadi; brauzer ovozi ishlatilmoqda.','AI ovozi mavjud emas; brauzer ovozi ishlatilmoqda.')}</small>}<progress value={result?100:test?index/tasks.length*100:stage/8*100} max={100}/>{error&&<p className="error" role="alert">{error}<Button onClick={start}>Qayta urinish</Button></p>}{!session&&<p>{busy?t('Preparing your lesson…','Dars tayyorlanmoqda…'):t('Reopen or retry this lesson.','Darsni qayta oching.')}</p>}
 {session&&!result&&<>{!test&&stage===0&&<><h2>{t('Let’s begin','Boshlaymiz')}</h2><p>{t('Learn words, explore structures, practise and speak.','So‘zlarni o‘rganing, tuzilmalarni tushuning, mashq qiling va gapiring.')}</p></>}{!test&&stage===1&&<div className="vocabulary-cards">{content?.words.map(w=><article className="assignment" key={w.word}><h2>{w.word}</h2><p>{w.meaning}</p><p>{w.example}</p><Button variant="outline" onClick={()=>say(w.word+'. '+w.example,rate)}>🔊 Listen</Button></article>)}</div>}{!test&&stage===2&&<><p className="preserve">{content?.explanation}</p>{content?.models.map(s=><article className="assignment" key={s}><p>{s}</p><Button variant="outline" onClick={()=>say(s,rate)}>🔊 Listen</Button></article>)}</>}
 {stage===3&&q&&<><small>{index+1}/{tasks.length} {q.review?t('· Review a difficult task','· Qiynalgan mashqni takrorlash'):''}</small><h2>{taskInstruction(q)}</h2>{q.kind==='letters'&&<p>{q.prompt}</p>}{q.audio&&<Button variant="outline" onClick={()=>say(q.audio!,rate,'en')}>🔊 Listen</Button>}<TaskCard q={q} answer={answer} onChange={setAnswer} disabled={checked}/>{checked&&<p className={correct(q,answer)?'feedback correct':'feedback wrong'}>{correct(q,answer)?t('Well done!','Ofarin!'):t('Incorrect. Try again.','Noto‘g‘ri. Qayta urinib ko‘ring.')}</p>}<div className="actions">{!checked?<Button data-answer-primary disabled={!answer.trim()} onClick={()=>{setChecked(true);setFirst(v=>{const n=[...v];if(n[index]===undefined)n[index]=answer;return n});stopVoice()}}>{t('Check','Tekshirish')}</Button>:<><Button variant="outline" onClick={()=>{setChecked(false);setAnswer('')}}>{t('Try again','Qayta urinish')}</Button><Button data-answer-primary onClick={()=>{const next=[...answers,answer];setAnswers(next);if(index===tasks.length-1){setStage(test?7:4)}else setIndex(index+1);setAnswer('');setChecked(false)}}>{t('Next','Keyingi')}</Button></>}</div></>}
 {!test&&(stage===4||stage===5)&&<><div className="chat-history">{chat.map((m,i)=><article className={'chat-bubble '+m.role} key={i}><small>{m.role==='ai'?'Zamon AI':t('You','Siz')}</small><p className="preserve">{m.text}</p>{m.role==='ai'&&<button onClick={()=>say(m.text,rate)}>🔊</button>}</article>)}</div><Button disabled={busy} onClick={()=>{stopVoice();rec.current?.abort();rec.current=record(text=>{setChatInput(text);sendChat(text)},setError)}}>🎙 {t('Speak to AI','AI bilan gaplashish')}</Button>{stage===4&&<><textarea rows={2} value={chatInput} onChange={e=>setChatInput(e.target.value)} placeholder={t('Or type your conversation reply','Yoki suhbat javobini yozing')}/><Button disabled={busy||!chatInput.trim()} onClick={()=>sendChat(chatInput)}>{t('Send','Yuborish')}</Button></>}<p>{t('Use your microphone for speaking. The transcript is approximate.','Speaking uchun mikrofondan foydalaning. Tanilgan matn taxminiy.')}</p></>}
 {!test&&stage===6&&<><h2>{t('Review','Takrorlash')}</h2><p className="preserve">{content?.explanation}</p>{content?.words.map(w=><details key={w.word}><summary>{w.word}</summary><p>{w.meaning} — {w.example}</p></details>)}</>}
 {stage===7&&<><h2>{test?t('Test completed','Test tugadi'):t('How was your lesson?','Dars qanday bo‘ldi?')}</h2>{!test&&<div className="options">{['Easy','Good','Difficult'].map(v=><button className={rating===v?'selected':''} key={v} onClick={()=>setRating(v)}>{v}</button>)}</div>}<Button disabled={busy||!test&&!rating} onClick={finish}>{busy?t('Saving…','Saqlanmoqda…'):t('Finish','Tugatish')}</Button></>}
 {!test&&stage!==3&&stage!==7&&<Button disabled={busy||(stage===4||stage===5)&&!chat.some(m=>m.role==='user')} onClick={()=>setStage(stage+1)}>{t('Continue','Davom etish')}</Button>}<AskTeacher book={book} unit={unit} lesson={lesson} uz={uz}/></>}
 {result&&<><h2>{result.score}/{result.total}</h2><p>{result.completed?t('Completed. Your teacher approves the next Unit.','Tugallandi. Keyingi Unitni o‘qituvchi tasdiqlaydi.'):t('Practise the difficult tasks and try again.','Qiynalgan mashqlarni takrorlab, qayta urinib ko‘ring.')}</p><Button onClick={onBack}>{t('Back to Unit','Unitga qaytish')}</Button></>}
 </section>
}
