import {randomBytes,createHmac,timingSafeEqual} from 'node:crypto';
import {AppError,activateTeacher,claimPendingTeacher,createAdministrator,db,digest,fail,hashPassword,mutation,safeUser,textValue,verifyPassword} from '@/lib/school-server';
import {centerContext,legacyCenter,schoolScope} from '@/lib/center-context';
import {requiredLessons} from '@/lib/lessons';
import {books} from '@/lib/catalog';
export const runtime='nodejs';
function equal(a:string,b:string){const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y)}
function secure(req:Request){return req.headers.get('x-forwarded-proto')==='https'||new URL(req.url).protocol==='https:'?'; Secure':''}
function signature(value:string){const secret=process.env.OWNER_ACCESS_CODE||process.env.TEACHER_ACCESS_CODE;if(!secret)throw new AppError('Registration is not configured.',503);return createHmac('sha256',secret).update(value).digest('hex')}
async function center(id:string){if(id===legacyCenter)return{id,name:'Zamon',teacher_code_hash:process.env.TEACHER_ACCESS_CODE?digest(process.env.TEACHER_ACCESS_CODE.trim()):'',administrator_code_hash:process.env.ADMINISTRATOR_ACCESS_CODE?digest(process.env.ADMINISTRATOR_ACCESS_CODE.trim()):''};const rows=await db('school_centers','GET',undefined,`id=eq.${encodeURIComponent(id)}`);if(!rows[0]||rows[0].disabled)throw new AppError('Choose an available learning centre.');return rows[0]}
async function signIn(req:Request,r:any){const token=randomBytes(32).toString('hex');await db('school_sessions','POST',{token:digest(token),user_id:r.id,expires_at:new Date(Date.now()+30*864e5).toISOString()});return Response.json({user:safeUser(r),loggedIn:true},{headers:{'Set-Cookie':`school_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=2592000${secure(req)}`,'Cache-Control':'no-store'}})}
export async function GET(){return schoolScope(async()=>{try{const rows=await db('school_centers');return Response.json({centers:[{id:legacyCenter,name:'Zamon'},...rows.filter((r:any)=>!r.disabled&&r.id!==legacyCenter).map((r:any)=>({id:r.id,name:r.name}))]},{headers:{'Cache-Control':'no-store'}})}catch(e){return fail(e)}})}
export async function POST(req:Request){return schoolScope(async()=>{try{
 mutation(req);const d=await req.json();
 if(d.action==='verifyTeacherCode'){
  const code=typeof d.code==='string'?d.code.trim():'',owner=process.env.OWNER_ACCESS_CODE?.trim();
  if(owner&&[process.env.TEACHER_ACCESS_CODE?.trim(),process.env.ADMINISTRATOR_ACCESS_CODE?.trim()].includes(owner))throw new AppError('Owner code must differ from Teacher and Centre Manager codes.',503);
  if(owner&&owner.length>=12&&equal(digest(code),digest(owner))){let rows=await db('school_users','GET',undefined,'identity=eq.__platform_owner__');if(!rows[0]){try{rows=await db('school_users','POST',{identity:'__platform_owner__',first_name:'Owner',last_name:'',role:'owner',center_id:'platform',book:'essential',unlocked_unit:1})}catch(e){rows=await db('school_users','GET',undefined,'identity=eq.__platform_owner__');if(!rows[0])throw e}}return signIn(req,rows[0])}
  const who=digest('teacher-code:'+(req.headers.get('x-nf-client-connection-ip')||req.headers.get('x-forwarded-for')?.split(',')[0]||'local'));if(!await db('rpc/school_login_guard','POST',{who}))throw new AppError('Too many incorrect attempts. Try again in 15 minutes.',429);
  const c=await center(textValue(d.centerId,100));let role='';const manager=process.env.ADMINISTRATOR_ACCESS_CODE?.trim(),teacher=process.env.TEACHER_ACCESS_CODE?.trim();if(manager&&manager.length>=12&&equal(digest(code),digest(manager)))role='administrator';else if(teacher&&teacher.length>=12&&equal(digest(code),digest(teacher)))role='teacher';if(!role)throw new AppError('The code is incorrect for this learning centre.',403);
  const value=[Date.now()+600000,randomBytes(24).toString('hex'),role,c.id].join('.');return Response.json({ok:true,role},{headers:{'Set-Cookie':`teacher_registration=${value}.${signature(value)}; HttpOnly; SameSite=Strict; Path=/api/auth; Max-Age=600${secure(req)}`,'Cache-Control':'no-store'}})
 }
 const first=textValue(d.firstName,60),last=textValue(d.lastName,60),password=textValue(d.password,128);if(password.length<8)throw new AppError('Use a password with at least 8 characters.');
 const name=(first+' '+last).normalize('NFKC').toLowerCase().replace(/\s+/g,' ').replace(/[‘’ʻʼ]/g,"'");
 if(!await db('rpc/school_login_guard','POST',{who:digest('login:'+name)}))throw new AppError('Too many attempts. Try again in 15 minutes.',429);
 if(d.action==='login'){
  const [old,indexed]=await Promise.all([db('school_users','GET',undefined,`identity=eq.${encodeURIComponent(name)}`),db('school_users','GET',undefined,`login_name=eq.${encodeURIComponent(name)}`)]);const candidates=[...new Map([...old,...indexed].map((r:any)=>[r.id,r])).values()].filter((r:any)=>r.role!=='owner'&&r.password_hash&&verifyPassword(password,r.password_hash));
  if(candidates.length!==1)throw new AppError(candidates.length?'More than one profile uses this name and password. Ask Owner to reset one password.':'The name or password is incorrect.',401);
  const r:any=candidates[0];if(r.disabled)throw new AppError('Your account is disabled.',403);await center(r.center_id||legacyCenter);if(d.role==='teacher'&&!['teacher','administrator'].includes(r.role))throw new AppError('This is not a teacher account.',403);return signIn(req,r);
 }
 const c=await center(textValue(d.centerId,100));const scope=centerContext.getStore()!;scope.centerId=c.id;const identity=c.id===legacyCenter?name:c.id+'|'+name;
 let rows=await db('school_users','GET',undefined,`identity=eq.${encodeURIComponent(identity)}`),r=rows[0];
 if(d.action==='registerTeacher'){
  const ticket=req.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith('teacher_registration='))?.slice(21)||'';const [expires,nonce,role,centerId,sig]=ticket.split('.');const value=[expires,nonce,role,centerId].join('.');if(centerId!==c.id||Number(expires)<=Date.now()||Number(expires)>Date.now()+600000||!nonce||!['teacher','administrator'].includes(role)||!sig||!equal(signature(value),sig))throw new AppError('Enter your centre registration code first.',403);
  if(role==='administrator'){if(r&&(r.role!=='admin'||!verifyPassword(password,r.password_hash)))throw new AppError('This name is already registered.',409);const created=await createAdministrator({identity,login_name:name,first_name:first,last_name:last,password_hash:hashPassword(password),book:'essential',unlocked_unit:1},r?.password_hash||null);if(!created)throw new AppError('Centre Manager already exists. Sign in.',409);r=created}
  else if(r){if(r.role!=='teacher'||r.password_hash)throw new AppError('This name is already registered. Sign in.',409);r=await claimPendingTeacher(identity,hashPassword(password));if(!r)throw new AppError('Could not activate teacher.',409)}
  else [r]=await db('school_users','POST',{identity,login_name:name,first_name:first,last_name:last,password_hash:hashPassword(password),role,book:'essential',unlocked_unit:1,start_unit:1,start_lesson:1});
 }else if(d.action==='activateTeacher'){if(c.id!==legacyCenter)throw new AppError('Use your centre code.');r=await activateTeacher(identity,textValue(d.invite,128),hashPassword(password));if(!r)throw new AppError('Invitation is unavailable.',403)}
 else if(d.action==='register'){if(r)throw new AppError('This name is already registered. Sign in.',409);if(d.role!=='student')throw new AppError('Choose Student.',403);const book=books.find(x=>x.id===d.book),unit=Number(d.unit),step=Number(d.startLesson||1);if(!book||!Number.isInteger(unit)||unit<1||unit>book.units.length||!Number.isInteger(step)||step<1||step>requiredLessons(book.id,unit).length)throw new AppError('Choose your book, Unit and lesson.');[r]=await db('school_users','POST',{identity,login_name:name,first_name:first,last_name:last,password_hash:hashPassword(password),role:'student',book:book.id,unlocked_unit:unit,start_unit:unit,start_lesson:step})}
 else if(!r||!r.password_hash||!verifyPassword(password,r.password_hash))throw new AppError('The centre, name or password is incorrect.',401);
 if(r.disabled)throw new AppError('Your account is disabled.',403);if(d.role==='teacher'&&!['teacher','administrator'].includes(r.role))throw new AppError('This is not a teacher account.',403);return signIn(req,r)
}catch(e){return fail(e)}})}
export async function DELETE(req:Request){return schoolScope(async()=>{try{mutation(req);const token=req.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith('school_session='))?.split('=')[1];if(token)await db('school_sessions','DELETE',undefined,`token=eq.${digest(token)}`);return Response.json({ok:true},{headers:{'Set-Cookie':'school_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'}})}catch(e){return fail(e)}})}
