export const unavailable='Saytning umumiy Gemini xizmati hali ulanmagan. Sayt egasi serverga Gemini kalitini ulashi kerak. Oddiy mashqlar kalitsiz ishlaydi.';
export function key(_provided?:unknown){const candidate=process.env.GEMINI_API_KEY;return typeof candidate==='string'&&/^[A-Za-z0-9._-]{20,512}$/.test(candidate)?candidate:undefined;}
export function sameOrigin(req:Request){const origin=req.headers.get('origin');return !origin||new URL(origin).host===(req.headers.get('host')||new URL(req.url).host);}
export function modelName(provided?:unknown){const m=(typeof provided==='string'?provided:process.env.GEMINI_MODEL)?.trim().replace(/^models\//,'');return typeof m==='string'&&/^gemini-[a-zA-Z0-9.-]{1,80}$/.test(m)?m:'gemini-3.5-flash-lite';}
export async function gemini({apiKey,model,instructions,parts,schema,maxTokens=4000}:{apiKey:string;model?:string;instructions:string;parts:any[];schema?:object;maxTokens?:number}):Promise<string>{
 const res=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${modelName(model)}:generateContent`,{method:'POST',headers:{'x-goog-api-key':apiKey,'Content-Type':'application/json'},body:JSON.stringify({systemInstruction:{parts:[{text:instructions}]},contents:[{role:'user',parts}],generationConfig:{maxOutputTokens:maxTokens,temperature:.2,...(schema?{responseMimeType:'application/json',responseJsonSchema:schema}:{})}}),signal:AbortSignal.timeout(60000)});
 const data:any=await res.json();if(!res.ok){if(res.status===429)throw new Error('Gemini limiti tugagan. Birozdan keyin urinib ko‘ring yoki API kvotasini tekshiring.');if(res.status===403||res.status===401||res.status===400)throw new Error('Gemini kaliti yoki model ruxsati noto‘g‘ri. Sayt egasi serverdagi kalitni tekshirishi kerak.');if(res.status===404&&!model){const list=await fetch('https://generativelanguage.googleapis.com/v1beta/models',{headers:{'x-goog-api-key':apiKey},signal:AbortSignal.timeout(10000)});if(list.ok){const available=await list.json();const candidates=(available.models||[]).filter((m:any)=>m.supportedGenerationMethods?.includes('generateContent')&&/flash/.test(m.name)&&!/(tts|image|live|audio|embedding)/.test(m.name));const selected=candidates.find((m:any)=>/flash$/.test(m.name))||candidates[0];if(selected)return gemini({apiKey,model:selected.name.replace(/^models\//,''),instructions,parts,schema,maxTokens});}}if(res.status===404)throw new Error('Gemini modeli mavjud emas. .env.local ichida GEMINI_MODEL=gemini-3.5-flash-lite qilib, serverni qayta ishga tushiring.');throw new Error('Gemini hozir javob bermadi. Yana urinib ko‘ring.');}
 const text=(data.candidates?.[0]?.content?.parts||[]).filter((p:any)=>typeof p.text==='string'&&!p.thought).map((p:any)=>p.text).join('\n');if(!text)throw new Error('Gemini javob qaytarmadi. So‘rovni soddalashtirib yana urinib ko‘ring.');return text;
}
